sudo: false

language: python

# Environment variable for documentation deployment
# Change author email when website author changes
env:
  global:
  - ENCRYPTION_LABEL: "1909213e8aea"
  - COMMIT_AUTHOR_EMAIL: "pandolfovince@gmail.com"
  - DEVITO_LOGGING: "DEBUG"

matrix:
  include:
    - os: linux
      python: "3.6"
      env: DEVITO_ARCH=gcc-4.9 DEVITO_OPENMP=0
    - os: linux
      python: "3.6"
      env: DEVITO_ARCH=gcc-5 DEVITO_OPENMP=0
    - os: linux
      python: "3.6"
      env: DEVITO_ARCH=gcc-4.9 DEVITO_OPENMP=1 OMP_NUM_THREADS=2
    - os: linux
      python: "3.6"
      env: DEVITO_ARCH=gcc-4.9 DEVITO_OPENMP=0 DEVITO_BACKEND=yask
  allow_failures:
    - os: linux
      python: "2.7"
      env: DEVITO_ARCH=gcc-4.9 DEVITO_OPENMP=0
    - os: osx
      python: "2.7"
      env: DEVITO_ARCH=clang DEVITO_OPENMP=0

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test     # For gcc 4.9 and 5
    packages:
      - gcc-4.9
      - g++-4.9
      - gcc-5
      - g++-5

before_install:
  # Setup anaconda
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  - conda env create -q -f environment.yml python=$TRAVIS_PYTHON_VERSION
  - source activate devito
  - pip install -e .

before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  # pip install git+https://github.com/opesci/yask.git@v2_alpha-setup-py;
  - if [[ $DEVITO_BACKEND == 'yask' ]]; then
      conda install swig; cd ../;
      git clone https://github.com/opesci/yask.git;
      cd yask; git checkout v2_alpha;
      make compiler && make compiler-api; pip install -e .; cd ../devito;
    fi

script:
  - flake8 --builtins=ArgumentError .
  - py.test -vs tests/

  # Additional seismic operator tests
  - if [[ $DEVITO_BACKEND != 'yask' ]]; then
      DEVITO_BACKEND=foreign py.test -vs tests/test_operator.py -k TestForeign;
      python examples/seismic/benchmark.py test -P tti -so 4 -a -d 20 20 20 -n 5;
      python examples/seismic/benchmark.py test -P acoustic -a;
      python examples/seismic/acoustic/acoustic_example.py --full;
      python examples/seismic/acoustic/acoustic_example.py --constant --full;
      python examples/seismic/acoustic/gradient_example.py;
    fi

  # Test tutorial notebooks for the website using nbval
  - if [[ $DEVITO_BACKEND != 'yask' ]]; then py.test -vs --nbval examples/seismic/tutorials; fi
  - if [[ $DEVITO_BACKEND != 'yask' ]]; then py.test -vs --nbval examples/cfd; fi

  # Docs generation and deployment
  - sphinx-apidoc -f -o docs/ examples
  - sphinx-apidoc -f -o docs/ devito devito/yask/*
  - if [[ $DEVITO_ARCH == 'gcc-5' ]]; then ./docs/deploy.sh; fi
